/** Classic scripts the headless replay boots. Keep this aligned with tests that checksum a run. */

export const ENGINE_FILES = [
  "lib/lz-string.min.js",
  "lib/diff_match_patch.js",
  "lib/mousetrap.min.js",
  "common/util",
  "common/larn_config",
  "common/frame",
  "common/patch",
  "common/roll",
  "common/cloudflare",
  "common/movie",
  "common/live",
  "config",
  "larn",
  "main",
  "object",
  "options",
  "global",
  "monster",
  "monsterdata",
  "player",
  "mazes",
  "level",
  "create",
  "data",
  "parse",
  "buttons",
  "scores",
  "inventory",
  "aura",
  "movem",
  "action",
  "io",
  "display",
  "storedata",
  "store",
  "mcdopes",
  "savelev",
  "spells",
  "spellsinfo",
  "regen",
  "spheres",
  "help",
  "state",
  "bill",
  "altar",
  "fountain",
  "potion",
  "scroll",
  "stairs",
  "throne",
  "devmode",
  "gotw",
  "explore",
  "determinism",
  "party",
  "encounter",
];

/** Same concatenation the Edge Function bundle and the node tests must share. */
export const concatEngineFiles = (read) =>
  ENGINE_FILES.map((file) => {
    const rel = file.endsWith(".js") ? file : `${file}.js`;
    return `\n// Source: ${file}\n${read(rel)}\n`;
  }).join("\n");
