import {chromium,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const base=process.env.TEST_URL||'http://localhost:4178';
const response=await page.goto(base);
const expectedBundle=readFileSync('dist/index.html','utf8').match(/src="(\/assets\/[^"]+\.js)"/)[1];
expect(await response.text()).toContain(expectedBundle);
const engineResponse=await page.request.get(base+'/engine/game.js');
expect(engineResponse.status()).toBe(200);
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
expect(hash(await engineResponse.body())).toBe(hash(readFileSync('dist/engine/game.js')));
await expect(page.locator('#loading')).toBeHidden({timeout:20000});
await page.screenshot({path:'/tmp/ularn-final-title.png'});
await page.locator('#begin').click();await expect(page.locator('#hud')).toHaveJSProperty('hidden',false);
await page.waitForTimeout(500);
await page.screenshot({path:'/tmp/ularn-final-game.png'});
console.log(JSON.stringify({url:page.url(),status:response.status(),securityHeaders:{contentType:response.headers()['x-content-type-options'],referrer:response.headers()['referrer-policy']},graphics:await page.evaluate(()=>ularnGraphics.metrics()),errors},null,2));
expect(errors).toEqual([]);
await page.goto(base+'/engine/larn_local.html?ularn=true');await page.waitForTimeout(1500);
console.log('Classic fallback:',{title:await page.title(),errors});expect(errors).toEqual([]);
await browser.close();
